const neighborhoods =
    [
        "Alamos",
        "Alhambra",
        "Alta Suiza",
        "Alto Tablazo",
        "Altos de Capri",
        "Aranjuez",
        "Arboleda",
        "Arenillo",
        "Arrayanes",
        "Asturias",
        "Avanzada",
        "Argentina",
        "Asunción",
        "Américas",
        "Agustinos",
        "Alcázares",
        "Autónoma",
        "Amarillo",
        "Alférez Real",
        "Baja Suiza",
        "Bajo Tablazo",
        "Belén",
        "Bella Montaña",
        "Betania",
        "Bosque",
        "Bosques de Niza",
        "Bosques del Norte",
        "Barrio 20 de Julio",
        "Cámbulos",
        "Camelia",
        "Camilo Torres",
        "Campo Amor",
        "Campo Hermoso",
        "Castellana",
        "Centenario",
        "Centro",
        "Cervantes",
        "Chipre",
        "Colombia",
        "Colón",
        "Colseguros",
        "Comuneros",
        "Carola",
        "Cumbre",
        "Colinas",
        "Cedros",
        "Caribe",
        "Carmen",
        "Castilla Terminal",
        "Delicias",
        "Est. Uribe (Tú y Yo)",
        "Est. Uribe (CHEC)",
        "Estambul",
        "El Palmar",
        "Eucaliptos",
        "Enea",
        "Z. Industrial",
        "Estrella",
        "Fanny Gonzales",
        "Fátima",
        "Fundadores",
        "Florida",
        "Francia",
        "Fuente",
        "Galán",
        "Galería",
        "Gonzales",
        "Guamal",
        "Guayacanes",
        "Isabella",
        "Kennedy",
        "Laureles",
        "Leonora",
        "Liborio",
        "Lleras",
        "Lusitania",
        "Malahabar",
        "Malahabar Bajo",
        "Maltería",
        "Milán",
        "Minitas",
        "Morrogacho",
        "Molinos",
        "Nevado",
        "Nogales",
        "Ondas de Otún",
        "Palermo",
        "Palogrande",
        "Palonegro",
        "Panorama",
        "Parque del Agua",
        "Prado",
        "Peralonso",
        "Persia",
        "Paraíso",
        "Pio XII",
        "Porvenir",
        "Puertas del Sol",
        "Rambla",
        "Residencias",
        "Rosales",
        "Reserva Campestre",
        "Rincón de la Francia",
        "Sacatín",
        "Samaria",
        "Santos",
        "San Cayetano",
        "San Joaquín",
        "San Jorge",
        "San José",
        "San Marcel",
        "San Sebastián",
        "Sancancio",
        "Santa Helena",
        "Sinaí",
        "Solferino",
        "Sol",
        "Sultana",
        "Toscana",
        "Topacio",
        "Trébol",
        "Uribe Av Paralela",
        "Vélez",
        "Versalles",
        "Villa Carmenza",
        "Viña del Río",
        "Villa Hermosa",
        "Villa Julia",
        "Villa Pilar",
        "Villamaría",
        "Pradera",
        "Turín",
        "Villa del Río",
        "Viveros"
    ] as const;


export { neighborhoods };

